const SUPABASE_URL="https://faujgnzagnktsmxbnmmx.supabase.co",SUPABASE_KEY="sb_publishable_BQVeY4ChsN9Vr1JzwXpcOw_RWALGfvj";
const MECH=["GIL","AMAURI","SAMUEL","TIAGUINHO","TIAGO"];const COL={GIL:"gil_count",AMAURI:"amauri_count",SAMUEL:"samuel_count",TIAGUINHO:"tiaguinho_count",TIAGO:"tiago_count"};const AV={GIL:"gil_available",AMAURI:"amauri_available",SAMUEL:"samuel_available",TIAGUINHO:"tiaguinho_available",TIAGO:"tiago_available"};
const EMP_DEFAULT=[
{id:"CILIANO",nome:"Ciliano",seg_in:"07:30",seg_out:"18:00",sab_in:"07:30",sab_out:"16:00",alm_in:"13:00",alm_out:"14:30"},
{id:"GEOVANA",nome:"Geovana",seg_in:"07:30",seg_out:"18:00",sab_in:null,sab_out:null,alm_in:"12:00",alm_out:"13:00"},
{id:"DEICIANE",nome:"Deiciane",seg_in:"07:30",seg_out:"12:30",sab_in:null,sab_out:null,alm_in:null,alm_out:null},
{id:"JESSICA",nome:"Jéssica",seg_in:"08:00",seg_out:"18:00",sab_in:"08:00",sab_out:"16:00",alm_in:"12:00",alm_out:"13:30"},
{id:"EZEQUIEL",nome:"Ezequiel",seg_in:"07:30",seg_out:"18:00",sab_in:"07:30",sab_out:"16:00",alm_in:"12:30",alm_out:"14:00"},
{id:"RUBENS",nome:"Rubens",seg_in:"07:30",seg_out:"18:00",sab_in:null,sab_out:null,alm_in:"12:00",alm_out:"13:00"}];
let db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY), oil={current:0,counts:{},avail:{},history:[]}, employees=[],points=[],credits={};
const $=id=>document.getElementById(id), toast=s=>{let e=$("toast");e.textContent=s;e.style.display="block";clearTimeout(window._t);window._t=setTimeout(()=>e.style.display="none",2500)};
function today(){return new Date().toLocaleDateString("en-CA",{timeZone:"America/Fortaleza"})} function mins(s){if(!s)return null;let [h,m]=s.split(":").map(Number);return h*60+m} function hh(m){let sign=m<0?"-":"+",x=Math.abs(Math.round(m)),h=Math.floor(x/60),mm=x%60;return `${sign}${String(h).padStart(2,"0")}:${String(mm).padStart(2,"0")}`} function dt(v){return new Date(v).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}
async function loadOil(){let c=await db.from("controle").select("*").eq("id",1).maybeSingle();if(c.data){oil.current=c.data.current_index||0;MECH.forEach(m=>{oil.counts[m]=c.data[COL[m]]||0;oil.avail[m]=c.data[AV[m]]!==false})}let h=await db.from("historico").select("*").order("created_at",{ascending:false}).limit(20);oil.history=h.data||[];renderOil()}
function next(){let a=MECH.map((m,i)=>({m,i,c:oil.counts[m]||0})).filter(x=>oil.avail[x.m]);if(!a.length)return oil.current;let n=Math.min(...a.map(x=>x.c));return a.find(x=>x.c===n).i}
async function oilAction(m,delta){let u={[COL[m]]:(oil.counts[m]||0)+delta,current_index:next(),updated_at:new Date().toISOString()};let r=await db.from("controle").update(u).eq("id",1);if(r.error)return toast(r.error.message);await db.from("historico").insert({mecanico:m,acao:delta>0?"trocou óleo":"correção -1",delta});await loadOil();toast("Registro salvo")}
async function toggle(m){let r=await db.from("controle").update({[AV[m]]:!oil.avail[m],updated_at:new Date().toISOString()}).eq("id",1);if(r.error)return toast(r.error.message);await loadOil()}
function renderOil(){let cur=MECH[oil.current]||"GIL";$("currentName").textContent=cur;$("sequence").innerHTML=MECH.map((m,i)=>`<div class="sequence-item ${i===oil.current?"active":""}"><span class="number">${i+1}</span><b>${m}</b><span>${oil.counts[m]||0} trocas</span></div>`).join("");$("mechanics").innerHTML=MECH.map(m=>`<div class="mechanic"><span><b>${m}</b><span class="status ${oil.avail[m]?"available":"unavailable"}">${oil.avail[m]?"● DISPONÍVEL":"● OCUPADO"}</span></span><span><button class="secondary" onclick="toggle('${m}')">${oil.avail[m]?"OCUPAR":"LIBERAR"}</button> ${oil.counts[m]||0}</span></div>`).join("");$("history").innerHTML=oil.history.map(x=>`<div class="history">${dt(x.created_at)} — ${x.mecanico} — ${x.acao}</div>`).join("")||"<div class='history'>Nenhuma ação.</div>"}
async function loadEmployees(){let e=await db.from("funcionarios").select("*").order("nome");employees=e.error?EMP_DEFAULT.map(x=>({...x})):e.data||EMP_DEFAULT;let d=today();let p=await db.from("pontos_funcionarios").select("*").gte("data",d.slice(0,7)+"-01").lte("data",d);points=p.data||[];let cr=await db.from("funcionarios_creditos").select("*");credits={};(cr.data||[]).forEach(x=>credits[x.funcionario_id]=x);renderEmployees()}
function expected(emp,date){let day=new Date(date+"T12:00:00-03:00").getDay();if(day===0)return 0;if(day===6)return mins(emp.sab_out)-mins(emp.sab_in);return mins(emp.seg_out)-mins(emp.seg_in)}
function worked(p,emp){if(!p?.chegada||!p?.saida)return null;let a=new Date(p.chegada),s=new Date(p.saida),total=Math.round((s-a)/60000);if(p.saida_almoco&&p.retorno_almoco)total-=Math.round((new Date(p.retorno_almoco)-new Date(p.saida_almoco))/60000);return total}
function monthBalance(id){let es=employees.find(e=>e.id===id);let ps=points.filter(p=>p.funcionario_id===id),bal=0,miss=0;ps.forEach(p=>{let exp=expected(es,p.data),w=worked(p,es);if(p.status==="FALTA")miss++;else if(p.status==="FERIADO_TRABALHADO"){}else if(w!==null)bal+=w-exp});let c=credits[id]||{dias:0};return {bal,miss,creditDays:c.dias||0}}
function renderEmployees(){$("employeeCards").innerHTML=employees.map(e=>{let b=monthBalance(e.id),credit=(credits[e.id]?.dias||0);return `<article class="employee-card"><div class="employee-name">${e.nome}</div><div class="muted">${e.seg_in}–${e.seg_out}${e.sab_in?` • sábado ${e.sab_in}–${e.sab_out}`:" • sem sábado"}</div><div class="employee-summary"><div class="stat"><small>SALDO HORAS</small><b class="${b.bal>=0?"positive":"negative"}">${hh(b.bal)}</b></div><div class="stat"><small>CRÉDITOS (DIAS)</small><b>${credit}</b></div><div class="stat"><small>FALTAS SEM CRÉDITO</small><b>${b.miss}</b></div><div class="stat"><small>ALMOÇO</small><b>${e.alm_in?`${e.alm_in}–${e.alm_out}`:"—"}</b></div></div><div class="employee-actions"><button class="secondary" onclick="openPoint('${e.id}')">LANÇAR HORÁRIOS</button><button class="secondary" onclick="openStatus('${e.id}')">FALTA / FERIADO / FOLGA</button></div></article>`}).join("")}
function modal(html){$("modal").innerHTML=`<div class="modal-box">${html}</div>`;$("modal").classList.remove("hidden")};function closeModal(){$("modal").classList.add("hidden")}
function openPoint(id,date=today()){let e=employees.find(x=>x.id===id),p=points.find(x=>x.funcionario_id===id&&x.data===date);modal(`<div class="modal-title">LANÇAR HORÁRIOS — ${e.nome}</div><div class="muted">Pode salvar incompleto. Ex.: somente a chegada. Depois você complementa.</div><div class="form-grid" style="margin-top:15px"><label class="field">Data<input id="pdate" type="date" value="${date}"></label><label class="field">Chegada<input id="pin" type="time" value="${time(p?.chegada)}"></label><label class="field">Saída almoço<input id="plout" type="time" value="${time(p?.saida_almoco)}"></label><label class="field">Retorno almoço<input id="plin" type="time" value="${time(p?.retorno_almoco)}"></label><label class="field">Saída<input id="pout" type="time" value="${time(p?.saida)}"></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">CANCELAR</button><button class="secondary" onclick="savePoint('${id}')">SALVAR</button></div>`)}
function time(v){return v?new Date(v).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit",hour12:false}):""}
function stamp(date,t){return t?`${date}T${t}:00-03:00`:null}
async function savePoint(id){let date=$("pdate").value,a=$("pin").value,lo=$("plout").value,li=$("plin").value,o=$("pout").value;if(!a&&!lo&&!li&&!o)return toast("Informe pelo menos um horário");let r=await db.from("pontos_funcionarios").upsert({funcionario_id:id,data:date,chegada:stamp(date,a),saida_almoco:stamp(date,lo),retorno_almoco:stamp(date,li),saida:stamp(date,o),status:null,updated_at:new Date().toISOString()},{onConflict:"funcionario_id,data"});if(r.error)return toast(r.error.message);closeModal();await loadEmployees();toast("Horários salvos")}
function openStatus(id){let e=employees.find(x=>x.id===id);modal(`<div class="modal-title">STATUS — ${e.nome}</div><div class="form-grid"><label class="field">Data<input id="sdate" type="date" value="${today()}"></label><label class="field">Opção<select id="stype"><option value="FALTA">NÃO VEIO TRABALHAR</option><option value="FERIADO_TRABALHADO">TRABALHOU EM FERIADO (+1 DIA)</option><option value="CREDITO">ADICIONAR FOLGAS/FÉRIAS</option></select></label><label class="field">Quantidade de dias<input id="sq" type="number" min="1" value="1"></label></div><div class="muted" style="margin-top:10px">Créditos de folga/férias e feriados trabalhados entram no mesmo saldo de dias. Uma falta consome primeiro esse saldo; só depois gera débito de horas/dia.</div><div class="modal-actions"><button class="secondary" onclick="closeModal()">CANCELAR</button><button class="secondary" onclick="saveStatus('${id}')">SALVAR</button></div>`)}
async function saveStatus(id){let date=$("sdate").value,type=$("stype").value,q=Math.max(1,Number($("sq").value)||1);if(type==="CREDITO"){let old=credits[id]?.dias||0,r=await db.from("funcionarios_creditos").upsert({funcionario_id:id,dias:old+q,updated_at:new Date().toISOString()},{onConflict:"funcionario_id"});if(r.error)return toast(r.error.message);await loadEmployees();closeModal();return toast(`+${q} dia(s) disponível(is)`) }if(type==="FERIADO_TRABALHADO"){let r=await db.from("pontos_funcionarios").upsert({funcionario_id:id,data:date,status:type,updated_at:new Date().toISOString()},{onConflict:"funcionario_id,data"});if(r.error)return toast(r.error.message);let old=credits[id]?.dias||0;r=await db.from("funcionarios_creditos").upsert({funcionario_id:id,dias:old+q,updated_at:new Date().toISOString()},{onConflict:"funcionario_id"});if(r.error)return toast(r.error.message);await loadEmployees();closeModal();return toast(`Feriado registrado: +${q} dia(s)`) }let old=credits[id]?.dias||0,used=Math.min(old,q);let remaining=old-used;r=await db.from("funcionarios_creditos").upsert({funcionario_id:id,dias:remaining,updated_at:new Date().toISOString()},{onConflict:"funcionario_id"});if(r.error)return toast(r.error.message);let r2=await db.from("pontos_funcionarios").upsert({funcionario_id:id,data:date,status:"FALTA",observacao:used?`Falta compensada por ${used} crédito(s).`:"Falta sem crédito."}, {onConflict:"funcionario_id,data"});if(r2.error)return toast(r2.error.message);await loadEmployees();closeModal();toast(used?`Falta compensada. Restam ${remaining} dia(s).`:"Falta registrada sem crédito")}
async function schedules(){modal(`<div class="modal-title">ALTERAR HORÁRIOS</div>${employees.map(e=>`<div class="form-grid" style="margin-bottom:10px"><label class="field">${e.nome}<input data-s="${e.id}" data-k="seg_in" value="${e.seg_in||""}"></label><label class="field">Saída<input data-s="${e.id}" data-k="seg_out" value="${e.seg_out||""}"></label></div>`).join("")}<div class="modal-actions"><button class="secondary" onclick="closeModal()">FECHAR</button></div><div class="muted">A tela completa de horários detalhados pode ser expandida depois; o registro manual não depende de horário previsto.</div>`)}
function switchPage(p){$("oilPage").classList.toggle("hidden",p!=="oil");$("employeePage").classList.toggle("hidden",p!=="employees");$("headerTitle").textContent=p==="oil"?"CONTROLE DE TROCA DE ÓLEO":"CONTROLE DE FUNCIONÁRIOS";$("menu").classList.add("hidden");if(p==="employees")loadEmployees()}
$("menuBtn").onclick=()=>$("menu").classList.toggle("hidden");document.querySelectorAll("#menu button[data-page]").forEach(b=>b.onclick=()=>switchPage(b.dataset.page));$("oilBtn").onclick=()=>oilAction(MECH[oil.current],1);$("busyBtn").onclick=()=>{let opts=MECH.map((m,i)=>`${i+1} — ${m}`).join("\n");let n=Number(prompt("CORRIGIR -1\n\n"+opts+"\n\nEscolha:"))-1;if(MECH[n])oilAction(MECH[n],-1)};$("tvBtn").onclick=()=>{let u=new URL(location.href);u.searchParams.set("painel","1");window.open(u,"_blank")};$("changeSchedules").onclick=schedules;setInterval(()=>$("clock").textContent=new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}),1000);$("clock").textContent=new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});loadOil();
