-- DAKAR MOTOS — Supabase
-- Cole tudo no SQL Editor e clique em RUN.

create table if not exists public.controle(
 id integer primary key,
 current_index integer not null default 0,
 gil_count integer not null default 0,
 amauri_count integer not null default 0,
 samuel_count integer not null default 0,
 tiaguinho_count integer not null default 0,
 tiago_count integer not null default 0,
 gil_available boolean not null default true,
 amauri_available boolean not null default true,
 samuel_available boolean not null default true,
 tiaguinho_available boolean not null default true,
 tiago_available boolean not null default true,
 updated_at timestamptz not null default now()
);
create table if not exists public.historico(
 id bigint generated by default as identity primary key,
 mecanico text not null, acao text not null, delta integer not null default 0,
 created_at timestamptz not null default now()
);
insert into public.controle(id) values(1) on conflict(id) do nothing;

alter table public.controle enable row level security;
alter table public.historico enable row level security;
drop policy if exists controle_select on public.controle;
create policy controle_select on public.controle for select to anon,authenticated using(true);
drop policy if exists controle_update on public.controle;
create policy controle_update on public.controle for update to anon,authenticated using(true) with check(true);
drop policy if exists historico_select on public.historico;
create policy historico_select on public.historico for select to anon,authenticated using(true);
drop policy if exists historico_insert on public.historico;
create policy historico_insert on public.historico for insert to anon,authenticated with check(true);
drop policy if exists historico_delete on public.historico;
create policy historico_delete on public.historico for delete to anon,authenticated using(true);

do $$ begin alter publication supabase_realtime add table public.controle; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.historico; exception when duplicate_object then null; end $$;

-- RESET AUTOMÁTICO DIÁRIO:
-- Esta função zera os contadores às 18:00 no horário de Brasília.
create or replace function public.reset_dakar_oleo()
returns void language sql security definer as $$
 update public.controle set
 current_index=0, gil_count=0, amauri_count=0, samuel_count=0, tiaguinho_count=0, tiago_count=0,
 updated_at=now() where id=1;
$$;

-- Se pg_cron estiver disponível no projeto, agenda 18:00 UTC-3 = 21:00 UTC.
-- Como o horário do Brasil (Fortaleza/Ceará) é UTC-3 sem horário de verão,
-- 21:00 UTC corresponde a 18:00 em Brasília.
do $$
begin
 if exists(select 1 from pg_available_extensions where name='pg_cron') then
   create extension if not exists pg_cron;
   if not exists(select 1 from cron.job where jobname='dakar-oleo-reset-18h') then
     perform cron.schedule('dakar-oleo-reset-18h','0 21 * * *','select public.reset_dakar_oleo()');
   end if;
 end if;
exception when others then
 null;
end $$;
